### ISSUE TITLE
A request to place the datasets and models on google cloud

### ISSUE THREAD

**Issue by zw-xxx** [fab-jul/RC-PyTorch#4]
Hello. I appreciate your open source of the code. It helps me a lot.
I get trouble when I try to obtain the get the Open Images Validation 500, training dataset and the trained-well model checkpoints. It returns `HTTPError: HTTP Error 404: Not Found` for all time. Would you mind place the datasets and models on google cloud? Thanks.

**Comment by fab-jul** [comment]
That's unfortunate, apparently my ETH account expired. I'll look into re-uploading the datasets.

**Comment by fab-jul** [comment]
The data should be available again. I will back it up to gCloud soon.

**Comment by fab-jul** [comment]
For now I made a local backup, will consider hosting options if ETH goes down again.
